name: deploy
on:
  workflow_call:
    outputs:
      status:
        description: "Deploy status"
        value: ${{ jobs.deploy.outputs.status }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.deploy.outcome }}
    steps:
      - name: Копирование репозитория
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Кэширование зависимостей
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Установка зависимостей
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        id: deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
