name: pull_request
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**/*'
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  build:
    uses: "./.github/workflows/build.yml"

  linter:
    needs: [ build ]
    uses: "./.github/workflows/lint.yml"

  e2e:
    needs: [ build ]
    uses: "./.github/workflows/e2e.yml"

  unit:
    needs: [ build ]
    uses: "./.github/workflows/unit.yml"
