on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**/*'
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Копирование репозитория
        uses: actions/checkout@v3
      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Кэширование зависимостей
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Установка зависимостей
        run: npm ci
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Копирование репозитория
        uses: actions/checkout@v3
      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Кэширование зависимостей
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Установка зависимостей
        run: npm ci
      - name: Запуски линтеров
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - name: Копирование репозитория
        uses: actions/checkout@v3
      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Кэширование зависимостей
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Установка зависимостей
        run: npm ci
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Установка зависимостей playwright
        run: npx playwright install --with-deps
      - name: Запуск e2e тестов
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-pr-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}
          path: playwright-report/
          retention-days: 30
      - name: Запуск unit тестов
        run: npm run test-ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: unit-tests-report-pr-${{ steps.previoustag.outputs.tag }}-${{ steps.vars.outputs.sha_short }}
          path: test-report.html
          retention-days: 30
