name: release

on:
  push:
    tags:
      - "v[0-9]+"
    paths-ignore:
      - '.github/**/*'

permissions:
  contents: read
  issues: write

jobs:
  build:
    uses: "./.github/workflows/build.yml"

  linter:
    needs: [build]
    uses: "./.github/workflows/lint.yml"

  e2e:
    needs: [build]
    uses: "./.github/workflows/e2e.yml"

  unit:
    needs: [build]
    uses: "./.github/workflows/unit.yml"

  deploy:
    needs: [build, linter, e2e, unit]
    if: success()
    uses: "./.github/workflows/deploy.yml"
    secrets: inherit

  create-issue:
    needs: [build, linter, e2e, unit, deploy]
    if: always()
    outputs:
      issue_number: ${{ steps.create-issue.outputs.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Копирование репозитория
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get runner url
        id: runner_url
        shell: bash
        run: |
          RUNNER_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "runner_url=${RUNNER_URL}" >> "$GITHUB_OUTPUT"
      - name: Changelog
        id: changelog
        shell: bash
        run: |
          CURRENT_VERSION=${{ github.ref_name }}
          PREVIOUS_VERSION=$(git describe --abbrev=0 --tags ${{ github.ref_name }}^)
          CHANGELOG=$(
          cat << EOF
          $(git log --pretty=format:"- %cs - [%h] - %s" ${CURRENT_VERSION}...${PREVIOUS_VERSION})
          EOF)
          echo "CHANGELOG<<EOF" >> "$GITHUB_OUTPUT"
          echo "${CHANGELOG}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - uses: JasonEtco/create-an-issue@v2
        if: always()
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
          VERSION: ${{ GITHUB.REF_NAME }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          LINTER_STATUS: ${{ needs.linter.outputs.status }}
          BUILD_STATUS: ${{ needs.build.outputs.status }}
          E2E_STATUS: ${{ needs.e2e.outputs.status }}
          UNIT_STATUS: ${{ needs.unit.outputs.status }}
          DEPLOY_STATUS: ${{ needs.unit.outputs.status }}
          RUNNER_URL: ${{ steps.runner_url.outputs.runner_url }}
        with:
          update_existing: true
          search_existing: all

  close_issue:
    runs-on: ubuntu-latest
    needs: [build, linter, e2e, unit, create-issue, deploy]
    if: success()
    steps:
      - name: Копирование репозитория
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Close Issue
        run: gh issue close --comment "Auto-closing issue" "${{ needs.create-issue.outputs.issue_number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
